### ISSUE TITLE
base16-project

### ISSUE THREAD

**Issue by JamyGolden** [tinted-theming/tinted-vim#55]
Hi @BonaBeavis, I'm contacting you because there is a group of us working on reviving the base16 project and I'm wondering if you'd be willing to join.

The discussion about a base16 Github organization initially started in 2016: https://github.com/chriskempson/base16/issues/74. With the disappearance of Chris Kempson the importance of the base16 organization is more important than ever to keep the project structured and thriving.

Seeing as you've been activate with base16 repo forks such as this one, are you interested in joining [github.com/base16-project](https://github.com/base16-project) and helping us maintain some of the projects? The work you've all done on this project (and the other base16 forks you've worked on) is great and we can bring it across to the other respective repos, [base16-project/base16-vim](https://github.com/base16-project/base16-vim) for example.

I managed to get hold of @fnune's email and sent them a message about this. They said that they weren't interested in being involved in base16 project work due to other commitments, but suggested contacting you about this.

Right now, communication around this is happening at https://github.com/base16-project/base16/issues/1 (Some of us are also on #base16 on Libera Chat [IRC] for more general discussions and hangouts)

Are you interested in maintaining any [base16-project](https://github.com/base16-project) repositories and being part of the organization?

**Comment by GordianDziwis** [comment]
I can maintain this project under the https://github.com/base16-project/ umbrella. This is a fork of Chris's https://github.com/chriskempson/base16-vim repo, where no commits in the last three years happened.

**Comment by fnune** [comment]
I can transfer the project if that's what yous decide!

**Comment by belak** [comment]
That would be awesome! I've gone ahead and removed our fork so yours can be transferred easily. Once that's done, I'm happy to re-add one or both of you as admins of that repo.

**Comment by fnune** [comment]
Trying to transfer:

`You don’t have the permission to create public repositories on base16-project`

Note that if I were to make the project private to then transfer it, it would lose its stars.

Before I forget it: I also maintain other forks of base16 projects kept fresh ahead of the originals:

- https://github.com/fnune/base16-shell
- https://github.com/fnune/base16-fzf

Are you interested in moving those over? I'm personally interested in reducing my involvement (even though it's not much), because I'm sure someone with more motivation to do it could improve it further.

**Comment by belak** [comment]
I invited both of you to the org (I guess it makes sense that you need to be a member to create new public repos).

We'd be happy to take those as well (though I don't use base16-fzf and I don't think we have a maintainer, so I'd probably just put it in base16-project-contrib) - I'll remove our fork of base16-shell so that can be transferred in as well.

**Comment by fnune** [comment]
The deed is done! I've transfered all 3 repos.

- https://github.com/base16-project/base16-fzf
- https://github.com/base16-project/base16-shell
- https://github.com/base16-project/base16-vim

They all run GitHub Actions, which I'm assuming will continue running without a problem. This may be worth taking a look at to check that they still run fine (they run every Sunday AFAIR).

If you need any context related to the existing stuff I can try to help! Although I also inherited them not long ago from the originals from @chriskempson.

**Comment by belak** [comment]
Great, thanks! I might look at getting the Actions to run using one of the builders maintained by the org, but I was meaning to set something like that up.

@fnune - Do you still want admin access to any of the repos, or will commit/management access be enough? Also, do you want me to list you as an official maintainer of any of them?

@BonaBeavis - I've also added you to the org and I'll update the main repo docs to mention you as a maintainer of the vim templates.

**Comment by fnune** [comment]
> Do you still want admin access to any of the repos, or will commit/management access be enough?

Commit/management is enough!

> Also, do you want me to list you as an official maintainer of any of them?

 I suppose the benefit would be that people can ping me for questions, so I would say yes. But it's totally up to you :slightly_smiling_face:

**Comment by belak** [comment]
Alright, it's been done! Thanks again!
